#ifndef __CR_QUICKLAKE_SERVICE_H
#define __CR_QUICKLAKE_SERVICE_H

enum {
	QUICKLAKE_CMD_ACK = 0,
	QUICKLAKE_CMD_INIT_DAEMON,
	QUICKLAKE_CMD_RESTORE_FILES,
	QUICKLAKE_CMD_UNMAP,
	QUICKLAKE_CMD_FINI,
};

#endif
